on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: install
        run: npm install

      - name: lint
        run: npm run lint

  test-js:
    runs-on: ubuntu-latest

    steps:
      - name: clone
        run: git clone https://github.com/ant-design/rodchen-king.git  --depth=1

      - name: install
        run: cd rodchen-king && npm install

      - name: fetch
        run: cd rodchen-king && npm run fetch:blocks --js

      - name: lint:fix
        run: cd rodchen-king && npm run lint:fix

      - name: lint
        run: cd rodchen-king && npm run lint
